#! /bin/sh
### BEGIN INIT INFO
# Provides: jekyll
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Jekyll
# Description: This file starts and stops Jekyll watcher
# 
### END INIT INFO

site_dir=/home/fedarch/faimsWebsite

PID_FILE=/var/run/jekyll.pid
LOG_FILE=/var/log/jekyll.log
PID_FILE2=/var/run/hookserve.pid
LOG_FILE2=/var/log/hookserve.log
JEKYLL=/home/fedarch/.rbenv/shims/jekyll

case "$1" in
 start)
   touch $LOG_FILE2
   chmod 666 $LOG_FILE2
   rm $PID_FILE2
   touch $LOG_FILE2
   #su fedarch -c "$JEKYLL build --source /home/fedarch/faimsWebsite --watch" >> $LOG_FILE &
   #echo $! > $PID_FILE
   su fedarch -c "$site_dir/hookserve --port=8888 --secret a8cd34b4-1b3e-11e6-9c23-00163ebf27ee $site_dir/hook.sh >> $LOG_FILE2 2>&1" &
   echo $! > $PID_FILE2
   echo "Jekyll STARTED"
   exit 0   
   ;;
 stop)
   #kill -TERM $(cat $PID_FILE)
   kill -TERM $(cat $PID_FILE2)
   echo "Jekyll STOPPED"
   exit 0   
   ;;
 restart)
   $0 stop
   $0 start
   exit 0
   ;;
 status)
   #ps -p `cat $PID_FILE` > /dev/null 2>&1 && echo "Jekyll Running" || echo "Jekyll Not Running"
   ps -p `cat $PID_FILE2` > /dev/null 2>&1 && echo "Hookserv Running" || echo "Hookserv Not Running"
   ;;
*)
   echo "Usage: $0 {start|stop|restart|status}"
   exit 1
esac
