- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Wiki"  
  url: "https://faimsproject.atlassian.net/wiki"
  title: "FAIMS Wiki"

- name: "Install FAIMS 2.5"
  url: "https://play.google.com/store/apps/details?id=au.edu.faims.mq.fieldresearch2"
  title: "Install FAIMS on your Android 6+"

#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
